export interface WordItem {
  id?: number;
  foreign_word: string;
  korean_meaning: string;
  notes?: string;
}

export const SAMPLE_WORDS: WordItem[] = [
  { foreign_word: 'ephemeral', korean_meaning: '덧없는, 일시적인', notes: '[ɪˈfemərəl] short-lived, transient' },
  { foreign_word: 'serendipity', korean_meaning: '뜻밖의 행운, 우연한 발견', notes: '[ˌserənˈdɪpəti] pleasant surprise' },
  { foreign_word: 'eloquent', korean_meaning: '유창한, 설득력 있는', notes: '[ˈeləkwənt] articulate, expressive' },
  { foreign_word: 'resilience', korean_meaning: '회복력, 탄력성', notes: '[rɪˈzɪliəns] toughness, adaptability' },
  { foreign_word: 'pragmatic', korean_meaning: '실용적인, 실제적인', notes: '[præɡˈmætɪk] practical, realistic' },
  { foreign_word: 'ubiquitous', korean_meaning: '어디에나 존재하는', notes: '[juːˈbɪkwɪtəs] omnipresent, everywhere' },
  { foreign_word: 'meticulous', korean_meaning: '꼼꼼한, 세심한', notes: '[məˈtɪkjələs] diligent, thorough' },
  { foreign_word: 'candid', korean_meaning: '솔직한, 거리낌 없는', notes: '[ˈkændɪd] frank, honest' },
  { foreign_word: 'lucid', korean_meaning: '명쾌한, 이해하기 쉬운', notes: '[ˈluːsɪd] clear, intelligible' },
  { foreign_word: 'tenacious', korean_meaning: '집요한, 끈질긴', notes: '[təˈneɪʃəs] persistent, stubborn' },
  { foreign_word: 'inevitable', korean_meaning: '불가피한, 피할 수 없는', notes: '[ɪnˈevɪtəbl] unavoidable, certain' },
  { foreign_word: 'benevolent', korean_meaning: '자비로운, 친절한', notes: '[bəˈnevələnt] kind, philanthropic' },
  { foreign_word: 'aesthetic', korean_meaning: '심미적인, 미적인', notes: '[esˈθetɪk] artistic, beautiful' },
  { foreign_word: 'ambiguous', korean_meaning: '모호한, 다의적인', notes: '[æmˈbɪɡjuəs] equivocal, unclear' },
  { foreign_word: 'diligent', korean_meaning: '근면한, 성실한', notes: '[ˈdɪlɪdʒənt] hardworking, conscientious' },
  { foreign_word: 'empathy', korean_meaning: '공감, 감정이입', notes: '[ˈempəθi] compassion, understanding' },
  { foreign_word: 'feasible', korean_meaning: '실행 가능한', notes: '[ˈfiːzəbl] practicable, workable' },
  { foreign_word: 'gregarious', korean_meaning: '사교적인, 군집성의', notes: '[ɡrɪˈɡeəriəs] sociable, companionable' },
  { foreign_word: 'homogeneous', korean_meaning: '동종의, 균일한', notes: '[ˌhɒməˈdʒiːniəs] uniform, identical' },
  { foreign_word: 'impartial', korean_meaning: '공정한, 편견 없는', notes: '[ɪmˈpɑːʃl] unbiased, neutral' },
  { foreign_word: 'judicious', korean_meaning: '신중한, 판단력 있는', notes: '[dʒuˈdɪʃəs] wise, sensible' },
  { foreign_word: 'kinetic', korean_meaning: '운동의, 활동적인', notes: '[kɪˈnetɪk] dynamic, moving' },
  { foreign_word: 'lethargic', korean_meaning: '무기력한, 혼수의', notes: '[ləˈθɑːdʒɪk] sluggish, inactive' },
  { foreign_word: 'mitigate', korean_meaning: '완화하다, 경감하다', notes: '[ˈmɪtɪɡeɪt] alleviate, ease' },
  { foreign_word: 'nuance', korean_meaning: '미묘한 차이', notes: '[ˈnjuːɑːns] subtle distinction' },
  { foreign_word: 'obscure', korean_meaning: '모호한, 잘 알려지지 않은', notes: '[əbˈskjʊə] ambiguous, cryptic' },
  { foreign_word: 'paradox', korean_meaning: '역설, 모순', notes: '[ˈpærədɒks] irony, contradiction' },
  { foreign_word: 'quaint', korean_meaning: '고풍스럽고 아기자기한', notes: '[kweɪnt] charming, attractive' },
  { foreign_word: 'redundant', korean_meaning: '불필요한, 중복되는', notes: '[rɪˈdʌndənt] superfluous, excessive' },
  { foreign_word: 'superfluous', korean_meaning: '여분의, 과잉의', notes: '[suːˈpɜːfluəs] redundant, extra' },
  { foreign_word: 'tranquil', korean_meaning: '고요한, 평온한', notes: '[ˈtræŋkwɪl] peaceful, calm' },
  { foreign_word: 'unprecedented', korean_meaning: '전례 없는', notes: '[ʌnˈpresɪdentɪd] unmatched, unique' },
  { foreign_word: 'versatile', korean_meaning: '다재다능한, 다용도의', notes: '[ˈvɜːsətaɪl] adaptable, flexible' },
  { foreign_word: 'wary', korean_meaning: '경계하는, 조심하는', notes: '[ˈweəri] cautious, vigilant' },
  { foreign_word: 'zealous', korean_meaning: '열성적인, 열광적인', notes: '[ˈzeləs] passionate, ardent' },
  { foreign_word: 'adversity', korean_meaning: '역경, 불운', notes: '[ədˈvɜːsəti] hardship, misfortune' },
  { foreign_word: 'brevity', korean_meaning: '간결함, 짧음', notes: '[ˈbrevəti] conciseness, succinctness' },
  { foreign_word: 'coherent', korean_meaning: '일관성 있는, 논리적인', notes: '[kəʊˈhɪərənt] logical, consistent' },
  { foreign_word: 'dauntless', korean_meaning: '겁 없는, 불굴의', notes: '[ˈdɔːntləs] fearless, brave' },
  { foreign_word: 'eclectic', korean_meaning: '다방면에 걸친, 절충적인', notes: '[ɪˈklektɪk] diverse, wide-ranging' },
  { foreign_word: 'frugal', korean_meaning: '검소한, 절약하는', notes: '[ˈfruːɡl] thrifty, economical' },
  { foreign_word: 'gratitude', korean_meaning: '감사, 고마움', notes: '[ˈɡrætɪtjuːd] thankfulness, appreciation' },
  { foreign_word: 'haphazard', korean_meaning: '무계획적인, 아무렇게나 하는', notes: '[ˌhæpˈhæzəd] random, unplanned' },
  { foreign_word: 'innate', korean_meaning: '타고난, 선천적인', notes: '[ɪˈneɪt] inborn, natural' },
  { foreign_word: 'juxtapose', korean_meaning: '나란히 놓다, 대조하다', notes: '[ˌdʒʌkstəˈpəʊz] place side by side' },
  { foreign_word: 'kindle', korean_meaning: '불붙이다, 불태우다', notes: '[ˈkɪndl] ignite, inspire' },
  { foreign_word: 'lucrative', korean_meaning: '수익성 있는, 돈벌이가 되는', notes: '[ˈluːkrətɪv] profitable, gainful' },
  { foreign_word: 'magnanimous', korean_meaning: '도량이 넓은, 관대한', notes: '[mæɡˈnænɪməs] generous, forgiving' },
  { foreign_word: 'nostalgia', korean_meaning: '향수, 그리움', notes: '[nɒˈstældʒə] longing, yearning' },
  { foreign_word: 'opulent', korean_meaning: '호화로운, 부유한', notes: '[ˈɒpjələnt] luxurious, wealthy' },
];
